# Generated by Django 5.1.1 on 2024-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Lastname')),
                ('first_name', models.CharField(max_length=100, verbose_name='Firtname')),
                ('birth_year', models.IntegerField(verbose_name='Birthyear')),
                ('club', models.CharField(max_length=100, verbose_name='Club')),
            ],
        ),
    ]
