# Generated by Django 5.1.1 on 2024-09-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='id_player',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ID hráče'),
        ),
    ]
